/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "20251218T161105"   // DateTime using ISO-8601 format
        " "                 // alignment
        "c61c7350"          // STLIB commit
        "--------"          // ADJ commit
        "8d5ea8df"          // Board commit
        // the '=' is used for unparsing
        ;
}