/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "20251223T122322"   // DateTime using ISO-8601 format
        " "                 // alignment
        "9e4fb9e2"          // STLIB commit
        "--------"          // ADJ commit
        "9c29450d"          // Board commit
        // the '=' is used for unparsing
        ;
}