#pragma once
#include "ST-LIB.hpp"

//Order packets for {{board}} -AUTOGENERATED CODE, DO NOT MODIFY-
class OrderPackets{
    {% for enum in enums %}enum class {{enum.name}}:uint8_t{
    {% for value in enum["values"] %}{{value}}={{loop.index0}}{%if not loop.last%},{%endif%}
    {% endfor %}};
    {% endfor %}

    {%for packet in packets%}bool {{packet.name}}_callback();
    {% endfor %}

    private:
        constexpr static size_t size={{size}};
        uint32_t id{0};
    public:
        std::array<StackOrder*,size> packets; 
        {%for packet in packets%}StackOrder* {{packet.name}};
        {% endfor %}
        
    OrderPackets({%for value in data %}{{value.type}} &{{value.name}}{%if not loop.last%},{%endif%}{%endfor%}}})
{

    {% for packet in packets %}{{packet.name}}=new StackOrder({{packet.id}},{{packet.name}}_callback{% if packet.data%},{{packet.data}}{% endif%});
    packets[id]={{packet.name}};
    id++;
    {% endfor %}
}
};