/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "{{ DateTimeISO8601 }}"   // DateTime using ISO-8601 format
        " "                 // alignment
        "{{ STLIB_COMMIT }}"          // STLIB commit
        "{{ ADJ_COMMIT}}"          // ADJ commit
        "{{ BOARD_COMMIT }}"          // Board commit
        // the '=' is used for unparsing
        {% for var_pair in variables -%}
        "{{var_pair.name}}={{var_pair.value}}" 
        {% endfor %};
}